/aruco_detector:
  ros__parameters:
    aruco_side: 0.15
    autostart: true
    best_effort_sub_qos: true
    image_sub_depth: 1
    input_topic: /camera/image_color
    output_topic: /targets
    stream_topic: /targets_stream
    transport: raw
    valid_ids:
      - 15
      - 23
    visual_data_topic: /targets_visual
    worker_cpu: -1
