/seppia/aruco_detector:
  ros__parameters:
    aruco_side: 0.51
    autostart: true
    base_frame: seppia/base_footprint
    best_effort_sub_qos: true
    centering_width: 150
    compute_position: true
    error_min: 0.13
    image_sub_depth: 12
    input_topic: /seppia/camera/image_raw
    node_namespace: /seppia
    output_topic: /aruco_output
    transport: compressed
