header_include_path: aruco_detector/aruco_detector.hpp
namespace: ArucoDetector
node_class_name: ArucoDetectorNode

params:
  aruco_side:
    type: double
    default_value: 0.1
    min_value: 0.0
    max_value: 2.0
    step: 0.001
    description: "Aruco side in meters."
    constraints: "Cannot be changed."
    read_only: true
    var_name: aruco_side

  autostart:
    type: bool
    default_value: false
    description: "Whether to start detection immediately."
    constraints: "Cannot be changed."
    read_only: true
    var_name: autostart

  best_effort_sub_qos:
    type: bool
    default_value: false
    description: "Whether to subscribe to the input topics with a best effort QoS."
    constraints: "Cannot be changed."
    read_only: true
    var_name: best_effort_sub_qos

  centering_width:
    type: integer
    default_value: 100
    min_value: 0
    max_value: 10000
    step: 1
    description: ""
    constraints: "Cannot be changed."
    read_only: true
    var_name: centering_width

  excluded_ids:
    type: integer_array
    default_value: [0]
    min_value: 0
    max_value: 10000
    step: 1
    description: "List of Arucos to be excluded."
    constraints: "Cannot be changed."
    read_only: true
    var_name: excluded_ids

  image_sub_depth:
    type: integer
    default_value: 1
    min_value: 0
    max_value: 100
    step: 1
    description: "QoS profile depth for the image subscription."
    constraints: "Cannot be changed."
    read_only: true
    var_name: image_sub_depth

  input_topic:
    type: string
    default_value: /input_topic
    description: "Camera topic name to subscribe to."
    constraints: "Cannot be changed."
    read_only: true
    var_name: input_topic

  output_topic:
    type: string
    default_value: /output_topic
    description: "Topic name to publish markers data on."
    constraints: "Cannot be changed."
    read_only: true
    var_name: output_topic

  stream_topic:
    type: string
    default_value: /stream_topic
    description: "Topic name to publish theora stream on."
    constraints: "Cannot be changed."
    read_only: true
    var_name: stream_topic

  transport:
    type: string
    default_value: raw
    description: "Image transport protocol."
    constraints: "Cannot be changed."
    read_only: true
    var_name: transport